### ISSUE TITLE
Error running with python3

### ISSUE THREAD

**Issue by smuzaffar** [pydata/bottleneck#266]
We are getting runtime error with python 3.6.4 and bottlenext 1.2.1. Simple tests fails [a]
```
import bottleneck
bottleneck.bench()
```
Looks like https://github.com/pydata/bottleneck/blob/master/bottleneck/benchmark/autotimeit.py#L6 is passing a float which python3 did not like.

[a]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<path>/py2-Bottleneck/1.2.1-nmpfii3/lib/python3.6/site-packages/bottleneck/benchmark/bench.py", line 77, in bench
    speed = timer(test['statements'], test['setups'])
  File "<path>py2-Bottleneck/1.2.1-nmpfii3/lib/python3.6/site-packages/bottleneck/benchmark/bench.py", line 87, in timer
    t0 = autotimeit(statements[0], setup)
  File "<path>/py2-Bottleneck/1.2.1-nmpfii3/lib/python3.6/site-packages/bottleneck/benchmark/autotimeit.py", line 7, in autotimeit
    number, time1 = autoscaler(timer, mintime)
  File "<path>/py2-Bottleneck/1.2.1-nmpfii3/lib/python3.6/site-packages/bottleneck/benchmark/autotimeit.py", line 15, in autoscaler
    time = timer.timeit(number)
  File "<path>/python3/3.6.4-pafccj/lib/python3.6/timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 16, in inner
TypeError: `n` must be an integer
```

**Comment by qwhelan** [comment]
Hi @smuzaffar - I recently took over maintainership and believe that's a valid issue with py3.6+. I'll be putting out a release candidate for `bottleneck=1.3.0` shortly.

**Comment by qwhelan** [comment]
This should work until the release later this week:
```
pip install --pre bottleneck==1.3.0rc1
```

**Comment by smuzaffar** [comment]
thanks @qwhelan , I confirm that it works.

**Comment by qwhelan** [comment]
Final release of 1.3.0 is now available. Thanks again for reporting and confirming the fix!
