### ISSUE TITLE
Bottleneck tries to install numpy-rc package

### ISSUE THREAD

**Issue by bumblebee211196** [pydata/bottleneck#368]
**Describe the bug**
While trying to install bottleneck using pip, bottleneck tries to install `numpy-1.20.0rc2` package which is not present in our private repository of python packages.

**To Reproduce**
To assist in reproducing the bug, please include the following:
1. pip install bottleneck==1.2.1
2. `Python` 3.6.3 and centOS 7
3. `pip` version 20.3.3
4. Only `bottleneck==1.2.1` is present in our server and `pip list` for numpy in our server results:
```
numpy-1.14.0-cp36-cp36m-manylinux1_x86_64.whl
numpy-1.14.5-cp36-cp36m-manylinux1_x86_64.whl
numpy-1.15.4-cp36-cp36m-manylinux1_x86_64.whl
numpy-1.16.2-cp36-cp36m-manylinux1_x86_64.whl
numpy-1.16.2-cp37-cp37m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
numpy-1.16.2-cp37-cp37m-manylinux1_i686.whl
numpy-1.16.2-cp37-cp37m-manylinux1_x86_64.whl
numpy-1.17.0-cp35-cp35m-manylinux1_i686.whl
numpy-1.17.2-cp35-cp35m-manylinux1_x86_64.whl
numpy-1.17.2-cp36-cp36m-manylinux1_x86_64.whl
numpy-1.17.2-cp37-cp37m-manylinux1_x86_64.whl
```

**Expected behaviour**
Bottleneck should be installed without any hassle.

**Additional context**
Stacktrace:
```
Downloading http://private-server/Bottleneck-1.2.1.tar.gz (105 kB)
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.6 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nn5sx6ux/bottleneck_154d6d02097a462ea3a48f951d681b1d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nn5sx6ux/bottleneck_154d6d02097a462ea3a48f951d681b1d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b5kzwfwa
       cwd: /tmp/pip-install-nn5sx6ux/bottleneck_154d6d02097a462ea3a48f951d681b1d/
  Complete output (68 lines):
  Traceback (most recent call last):
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
      yield saved
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
      _execfile(setup_script, ns)
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-ycyf471i/numpy-1.20.0rc2/setup.py", line 30, in <module>
      def prepare_modules():
  RuntimeError: Python version >= 3.7 required.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-nn5sx6ux/bottleneck_154d6d02097a462ea3a48f951d681b1d/setup.py", line 110, in <module>
      setup(**metadata)
    File "/usr/bin/python3.6/site-packages/setuptools/__init__.py", line 144, in setup
      _install_setup_requires(attrs)
    File "/usr/bin/python3.6/site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "/usr/bin/python3.6/site-packages/setuptools/dist.py", line 724, in fetch_build_eggs
      replace_conflicting=True,
    File "/usr/bin/python3.6/site-packages/pkg_resources/__init__.py", line 782, in resolve
      replace_conflicting=replace_conflicting
    File "/usr/bin/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in best_match
      return self.obtain(req, installer)
    File "/usr/bin/python3.6/site-packages/pkg_resources/__init__.py", line 1077, in obtain
      return installer(requirement)
    File "/usr/bin/python3.6/site-packages/setuptools/dist.py", line 791, in fetch_build_egg
      return cmd.easy_install(req)
    File "/usr/bin/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
      return self.install_item(spec, dist.location, tmpdir, deps)
    File "/usr/bin/python3.6/site-packages/setuptools/command/easy_install.py", line 705, in install_item
      dists = self.install_eggs(spec, download, tmpdir)
    File "/usr/bin/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
      return self.build_and_install(setup_script, setup_base)
    File "/usr/bin/python3.6/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
      self.run_setup(setup_script, setup_base, args)
    File "/usr/bin/python3.6/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
      run_setup(setup_script, args)
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
      raise
    File "/usr/local/lib/python3.6/contextlib.py", line 100, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/usr/local/lib/python3.6/contextlib.py", line 100, in __exit__
      self.gen.throw(type, value, traceback)
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
      saved_exc.resume()
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
      six.reraise(type, exc, self._tb)
    File "/usr/bin/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
      raise value.with_traceback(tb)
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
      yield saved
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
      yield
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
      _execfile(setup_script, ns)
    File "/usr/bin/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
      exec(code, globals, locals)
    File "/tmp/easy_install-ycyf471i/numpy-1.20.0rc2/setup.py", line 30, in <module>
      def prepare_modules():
  RuntimeError: Python version >= 3.7 required.
  ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Result: 1
  ExitValue from the task is : 1

```

**Comment by qwhelan** [comment]
@bumblebee211196 Does the same issue occur on Bottleneck 1.3?

**Comment by bumblebee211196** [comment]
@qwhelan We don't have bottleneck 1.3 in our private server. I will add it and try it once.

**Comment by bumblebee211196** [comment]
@qwhelan Facing the same problem with Bottleneck 1.3 as well

```
Collecting Bottleneck==1.3.0 (from -r requirements.txt (line 4))
  Downloading http://private-server/Bottleneck-1.3.0.tar.gz (87kB)
    100% |################################| 92kB 623kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-gk2od075/numpy-1.20.0rc2/setup.py", line 30, in <module>
        for d in dirs:
    RuntimeError: Python version >= 3.7 required.
```

**Comment by rgommers** [comment]
This has long since been resolved, there is nothing in `pyproject.toml` or `setup.py`/`setup.cfg` that causes a `numpy` pre-release to be pulled in. The most likely reason this happened is a pre-release version number usage in a dependency specifier (e.g., `install_requires=['numpy>=1.16rc2']` in `setup.py`). There is really no other way this could be caused by `bottleneck` itself.

Thank you for the report.
