### ISSUE TITLE
PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

### ISSUE THREAD

**Issue by europound** [pydata/bottleneck#375]
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ python -V
Python 3.8.5
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ pip -V
pip 21.0.1 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
wallets@wallets-TUF-Gaming:~/Downloads/btcrecover-master$ python3 -m btcrecover.test.test_passwords -v GPUTests
test_bitcoincore_OpenCL_JTR (__main__.Test08KeyDecryption) ... FAIL

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
test_bitcoincore_OpenCL_JTR_unicode (__main__.Test08KeyDecryption) ... FAIL

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
test_bitcoincore_OpenCL_JTR_low_interrupt_rate (__main__.Test08KeyDecryption) ... FAIL

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
test_bitcoincore_OpenCL_JTR_sli (__main__.Test08KeyDecryption) ... skipped 'requires two identical OpenCL devices'

======================================================================
FAIL: test_bitcoincore_OpenCL_JTR (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1677, in test_bitcoincore_OpenCL_JTR
    self.assertTrue(test_succeeded) #Check that at least one device successfully ran the test
AssertionError: False is not true

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

======================================================================
FAIL: test_bitcoincore_OpenCL_JTR_unicode (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1702, in test_bitcoincore_OpenCL_JTR_unicode
    self.assertTrue(test_succeeded)  # Check that at least one device successfully ran the test
AssertionError: False is not true

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

======================================================================
FAIL: test_bitcoincore_OpenCL_JTR_low_interrupt_rate (__main__.Test08KeyDecryption)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 82, in skip_or_test
    test_func(self)
  File "/home/wallets/Downloads/btcrecover-master/btcrecover/test/test_passwords.py", line 1727, in test_bitcoincore_OpenCL_JTR_low_interrupt_rate
    self.assertTrue(test_succeeded)  # Check that at least one device successfully ran the test
AssertionError: False is not true

Stdout:
GeForce GTX 1650 Ti  PyOpenCL Exception:  the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

----------------------------------------------------------------------
Ran 4 tests in 0.871s

FAILED (failures=3, skipped=1)

**Comment by rgommers** [comment]
This issue is unrelated to `bottleneck`, closing as invalid.
