### ISSUE TITLE
AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'

### ISSUE THREAD

**Issue by Kinzowa** [pydata/bottleneck#389]
Hello, i'm having an issue upgrading Bottleneck to the latest release, how could I fix that ?

```
pip3 freeze | grep Bottleneck
Bottleneck==1.2.1
```

I'm running Bottlenec 1.2.1 in a virtual env.

Thank you,

```
(env) username@ubuntu-2cpu-4gb-de-fra1:~/ta-lib$ pip3 install --upgrade bottleneck

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: bottleneck in /home/abc/.local/lib/python3.7/site-packages (1.2.1)
Collecting bottleneck
  Using cached Bottleneck-1.3.2.tar.gz (88 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/abc/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpho6m9d0z
       cwd: /tmp/pip-install-leodrmzz/bottleneck_481733e202a94aba8e54e1f5f2976f9e
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/abc/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 111, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 102, in _build_backend
      obj = getattr(obj, path_part)
  **AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'**
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/5b/08/278c6ee569458e168096f6b51019cc1c81c288da3d1026a22ee2ccead102/Bottleneck-1.3.2.tar.gz#sha256=20179f0b66359792ea283b69aa16366419132f3b6cf3adadc0c48e2e8118e573 (from https://pypi.org/simple/bottleneck/). Command errored out with exit status 1: /usr/bin/python3 /home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpho6m9d0z Check the logs for full command output.
  Using cached Bottleneck-1.3.1.tar.gz (88 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpg9n7_yns
       cwd: /tmp/pip-install-leodrmzz/bottleneck_0ef802af4c474eafa7af26b0847fdfa6
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 111, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 102, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/62/d0/55bbb49f4fade3497de2399af70ec0a06e432c786b8623c878b11e90d456/Bottleneck-1.3.1.tar.gz#sha256=451586370462cb623d6ad604a545d1e97fb51d2ab5252b1ac57350a83e494a28 (from https://pypi.org/simple/bottleneck/). Command errored out with exit status 1: /usr/bin/python3 /home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmpg9n7_yns Check the logs for full command output.
  Using cached Bottleneck-1.3.0.tar.gz (87 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /tmp/tmp0av1hbwa
       cwd: /tmp/pip-install-leodrmzz/bottleneck_9a0c26f662814defa5126bc5d52f99d9
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
      main()
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 111, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/fabulous/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 102, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
```

**Comment by Kinzowa** [comment]
I managed to install the package globally and it's now in my virtual environement. Not sure how it's possible ^^

```
(env) usernam@ubuntu-2cpu-4gb-de-fra1:~$ pip3 freeze | grep Bot
Bottleneck==1.3.2
```
